apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
  labels:
    name: createvolume
spec:
  containers:
  - name: alpine
    image: alpine
    restartPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /opt
      type: Directory