apiVersion: v1
kind: Pod
metadata:
  name: firstpod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: vol1
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: firstpvc