apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard # [ pd-standard | pd-ssd ]
  replication-type: none # [ none | regional-pd ]

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-ssd # [ pd-standard | pd-ssd ]
  replication-type: none # [ none | regional-pd ]